#Robocode Robot
#Tue May 26 16:10:14 GMT-03:00 2026
robocode.version=1.10.3
robot.author.name=
robot.classname=IAF.SudoKill
robot.codesize=848
robot.description=O rob\u00F4 SudoKill \u00E9 um tanque avan\u00E7ado.
robot.include.source=true
robot.version=1.0
